# -*- coding: utf-8 -*-
"""Account_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOf1duVVozJgNpcLQTHNnyNUtP-WtsiW
"""

!python main.py